import { appColors } from "../premetive/colors";

export const semanticColors = {
  surfacePrimary: appColors.gray0,
  surfacePrimaryInverted: appColors.gray900,
  surfacePage: appColors.extraColor1,
  surfaceSecondary: appColors.gray50,
  surfaceAction: appColors.blue500,
  surfaceActionLight: appColors.blue50,
  surfaceActionHover: appColors.blue400,
  surfaceActionPressed: appColors.blue700,
  surfaceActionHoverLight: appColors.blue50,
  surfaceDisabled: appColors.gray50,
  surfaceDisabledLight: appColors.gray100,
  surfaceSuccess: appColors.green50,
  surfaceErrorLight: appColors.red50,
  surfaceWarningLight: appColors.orange50,
  surfaceNormalLight: appColors.blue50,
  surfaceError: appColors.red100,
  surfaceWarning: appColors.orange100,

  textPrimary: appColors.gray500,
  textSecondary: appColors.gray300,
  textOnAction: appColors.gray0,
  textAction: appColors.blue500,
  textActionHover: appColors.blue400,
  textActionPressed: appColors.blue700,
  textDisabled: appColors.gray100,
  textOnDisabled: appColors.gray200,
  textSuccess: appColors.green100,
  textNormal: appColors.green100,
  textError: appColors.red100,
  textWarning: appColors.orange100,

  borderPrimary: appColors.gray500,
  borderPrimaryInverted: appColors.gray0,
  borderSecondary: appColors.gray300,
  borderTertiary: appColors.gray200,
  borderAction: appColors.blue500,
  borderActionLight: appColors.blue50,
  borderActionHover: appColors.blue400,
  borderActionPressed: appColors.blue700,
  borderOnDisabled: appColors.gray200,
  borderFocus: appColors.blue200,
  borderSuccess: appColors.green100,
  borderNormal: appColors.blue500,
  borderError: appColors.red100,
  borderWarning: appColors.orange100,

  iconPrimary: appColors.gray500,
  iconSecondary: appColors.gray200,
  iconTertiary: appColors.gray100,
  iconOnAction: appColors.gray0,
  iconAction: appColors.blue500,
  iconActionHover: appColors.blue400,
  iconActionPressed: appColors.blue700,
  iconOnDisabled: appColors.gray200,
  iconFocus: appColors.blue200,
  iconSuccess: appColors.green100,
  iconNormal: appColors.blue500,
  iconError: appColors.red100,
  iconWarning: appColors.orange100,
} as const;
